name: PR Review

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy_job:
    #if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: upload
          # Directory location of the application source code
          app_location: packages/docsite
          # Required token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_CREDENTIALS }}
          # Identical in use to output_location
          # app_artifact_location: dist
          # Token for interacting with the Github repository. Currently used only for commenting on Pull Requests.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Skips the build step for the application source code if set to true.
          skip_app_build: true

  #close_pull_request_job:
  #  if: github.event_name == 'pull_request' && github.event.action == 'closed'
  #  runs-on: ubuntu-latest
  #  name: Close Pull Request Job
  #  steps:
  #    - name: Close Pull Request
  #      id: closepullrequest
  #      uses: Azure/static-web-apps-deploy@v1
  #      with:
  #        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_RIVER_0AFDB141E }}
