# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  push:
    branches:
      - "main"
    paths:
      - "VERSION.txt"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Yarn Authenticate
      run: |-
        echo "npmRegistries:
          \"https://pkgs.dev.azure.com/peterlgerrard/_packaging/Testing/npm/registry/\":
            npmAlwaysAuth: true
            npmAuthIdent: ${{ secrets.PUBLISH_TOKEN }}
            # BASE64 peterlgerrard:PAT token"
    - run: |-
        yarn workspace @petergerrrard/css npm publish
        yarn workspace @petergerrrard/components npm publish
    
